
[mgr]
show_hidden = true


[opener]
edit = [
	{ run = '${EDITOR:-hx} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	
	{ run = 'hx %*', block = true,  desc = "code (block)",   for = "windows" },
]
open = [

	{ run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },


]

opencsv = [
  { run = "tw %s --separator ;", block = true,  desc = "Open csv with TW"},
]
[open]
prepend_rules = [

	{ url = "*.ini", use = "edit" },
	{ url = "*.toml", use = "edit" },
	{ url = "*.nXML", use = "open" },
	{ url = "*.nXML", use = "open" },
{ url = "*.csv", use = "opencsv" },
{ url = "*.xlsx", use = "opencsv" },


]
