
[mgr]
show_hidden = true


[opener]
edit = [
	{ run = '${EDITOR:-hx} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	
	{ run = 'hx %*', block = true,  desc = "code (block)",   for = "windows" },
]
open = [

	{ run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },

]

[open]
prepend_rules = [

	{ name = "*.ini", use = "edit" },
	{ name = "*.toml", use = "edit" },
	{ name = "*.nXML", use = "open" },


]
