{{ $lazygitVersion := "0.44.0"}}
[".local/bin/lazygit"]
  type = "archive-file"
  url = "https://github.com/jesseduffield/lazygit/releases/download/v{{ $lazygitVersion }}/lazygit_{{ $lazygitVersion }}_Linux_x86_64.tar.gz"
  path = "lazygit"

{{ $skmVersion := "0.8.6"}}
[".local/bin/skm"]
  type = "archive-file"
  url = "https://github.com/TimothyYe/skm/releases/download/v{{ $skmVersion }}/skm_{{ $skmVersion }}_Linux_x86_64.tar.gz"
  path = "skm"
