[general]
import = [
    "c:\\users\\osto\\.config\\alacritty\\themes\\themes\\deepspace.toml",
]
[terminal.shell]
program = "cmd"

[font]
normal = { family = "Hack Nerd Font"}
size = 12

[colors]

# Transparent background colors
transparent_background_colors = true

[window]

decorations = "None"
padding = {x=3, y=10}

[debug]
render_timer = false
persistent_logging = false
highlight_damage = false

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"