theme = "monokai_aqua"

[editor]
true-color = true
bufferline = "always"

[editor.indent-guides]
render = true 
character = "⸽"
skip-levels = 1

[keys.normal.C-y]

# Open the file(s) in the current window
y = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
# Open the file(s) in a vertical pane
v = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh vsplit"
# Open the file(s) in a horizontal pane
h = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh hsplit"

[keys.normal]

C-l = ":sh zellij run -c -f --width 80% --height 80% -- lazygit"
# g = ":run-shell-command zellij run -fc -- gitui"
