[[sources]]
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
# scope = ["python"]
path = "snippets/python/python.json"
[[sources.paths]]
path = "snippets/python/pydoc.json"

[[sources.paths]]
# scope = ["go"]
path = "snippets/go.json"

[[sources.paths]]
# scope = ["rust"]
path = "snippets/rust/rustdoc.json"

[[sources.paths]]
# scope = ["rust"]
path = "snippets/rust/rust.json"

[[sources.paths]]
path = "snippets/php/php.json"
[[sources.paths]]
path = "snippets/php/phpdoc.json"
