[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"



[manager]
prepend_keymap = [

	{ on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	# Hopping
	{ on = "e", run = "arrow -1", desc = "Previous file" },
	{ on = "n", run = "arrow 1", desc = "Next file" },
	# Navigation
	{ on = "m", run = "leave", desc = "Back to the parent directory" },
	{ on = "i", run = "enter", desc = "Enter the child directory" },
	# Linemode
	{ on = [ "l", "s" ], run = "linemode size",        desc = "Linemode: size" },
	{ on = [ "l", "p" ], run = "linemode permissions", desc = "Linemode: permissions" },
	{ on = [ "l", "b" ], run = "linemode btime",       desc = "Linemode: btime" },
	{ on = [ "l", "m" ], run = "linemode mtime",       desc = "Linemode: mtime" },
	{ on = [ "l", "o" ], run = "linemode owner",       desc = "Linemode: owner" },
	{ on = [ "l", "n" ], run = "linemode none",        desc = "Linemode: none" },
	{ on = [ "g", "a" ], run = "cd ~/AppData/Roaming",        desc = "AppData Roaming" },
 	{ on = [ "g", "l", "s" ], run = "cd c:/LocalRepos3/Env/System",        desc = "LV System" },
	{ on = [ "g", "l", "d" ], run = "cd c:/LocalRepos3/DUT_TC",        desc = "LV DUT TC" },

 
 	{ on = [ "!" ], run = 'shell "cmd.exe" --block',        desc = "Open PowerShell here" },
   	{ on = [ "p" ], run = 'plugin jump-to-char',        desc = "Jump to char" },
  	{ on = [ ";", "c" ], run = "shell --block 'chezmoi add %0'",        desc = "Chezmoi add" },
    	{ on = [ "T"], run = "plugin toggle-pane min-preview",        desc = "Chezmoi add" },
     	{ on = [ ";", "s" , "s" ], run = "shell --block 'svnst'",        desc = "Svn Status" },
	{ on = [ ";", "s" , "u" ], run = "shell --block 'svnup'",        desc = "Svn Update" },
 	{ on = [ ";", "s" , "l" ], run = "shell --block 'svnlog'",        desc = "Svn Log" },


]




