[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"



[manager]
prepend_keymap = [

	{ on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	# Hopping
	{ on = "e", run = "arrow -1", desc = "Previous file" },
	{ on = "n", run = "arrow 1", desc = "Next file" },
	# Navigation
	{ on = "m", run = "leave", desc = "Back to the parent directory" },
	{ on = "i", run = "enter", desc = "Enter the child directory" },
	# Linemode
	{ on = [ "l", "s" ], run = "linemode size",        desc = "Linemode: size" },
	{ on = [ "l", "p" ], run = "linemode permissions", desc = "Linemode: permissions" },
	{ on = [ "l", "b" ], run = "linemode btime",       desc = "Linemode: btime" },
	{ on = [ "l", "m" ], run = "linemode mtime",       desc = "Linemode: mtime" },
	{ on = [ "l", "o" ], run = "linemode owner",       desc = "Linemode: owner" },
	{ on = [ "l", "n" ], run = "linemode none",        desc = "Linemode: none" },
]

