[plugin]
deps = [{ use = "yazi-rs/plugins:full-border", rev = "c578505" }, { use = "llanosrocas/githead", rev = "bf150f3" }, { use = "AnirudhG07/rich-preview", rev = "9bcf154" }, { use = "yazi-rs/plugins:mime-ext", rev = "c578505" }]

[flavor]
deps = [{ use = "yazi-rs/flavors:catppuccin-frappe", rev = "d479f67" }, { use = "yazi-rs/flavors:catppuccin-latte", rev = "d479f67" }, { use = "yazi-rs/flavors:catppuccin-mocha", rev = "d479f67" }]
