# theme = "monokai_aqua"
theme = "dark_plus_oscar"

[editor]
mouse = true
true-color = true
bufferline = "always"
line-number = "relative"

[editor.soft-wrap]
enable = true



[editor.indent-guides]
render = true 
character = "⸽"
skip-levels = 1


# [keys.normal]

# Open the file(s) in the current window
# C-y = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
# Open the file(s) in a vertical pane
# v = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh vsplit"
# Open the file(s) in a horizontal pane
# h = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh hsplit"

[keys.normal]

C-y = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
C-k = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/rfvh open"
C-l = ":sh zellij run -c -f --width 80% --height 80% -- lazygit"
C-s = [":write"]
C-b = ["save_selection"]
C-q = ":q"
C-tab = ":bn"
ret = ["insert_mode","insert_newline"]
d = "delete_selection_noyank"
A-d = "delete_selection"
c = "change_selection_noyank"
A-c = "change_selection"


S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
 C-s = ["normal_mode", ":write"]


# [keys.normal.b]
# c = ":bc"

# [keys.normal.space]
[keys.normal."]"]
"]" = [":bn"]
[keys.normal."["]
"[" = [":bp"]


[keys.normal.";"]
b = ":sh heliz-wezterm.sh blame"
e = ":sh heliz-wezterm.sh explorer"
f = ":sh heliz-wezterm.sh fzf"
g = ":sh heliz-wezterm.sh lazygit"
o = ":sh heliz-wezterm.sh open"
r = ":sh heliz-wezterm.sh run"
s = ":sh heliz-wezterm.sh test_single"
t = ":sh heliz-wezterm.sh test_all"
w = ":sh zelix.sh explorer"
